### ISSUE TITLE
Analog Stick get's stuck 

### ISSUE THREAD

**Issue by legraphista** [sbidolach/mobile-gamepad#8]
Analog stick gets stuck on Latest Google Chrome on Android.
It catches movement for half a second then it stops responding to touch input.

Also tested on latest Firefox on Android and it works.

Here's a demo: https://goo.gl/photos/SaH3h9C2wXRMXyes6

**Comment by sbidolach** [comment]
Thanks @legraphista for good explanation what is wrong! It looks like they have changed something in new Google Chrome on Android. I'll try to analyze this what happened when I'll be less busy than I'm now :) If you need quick solution, I'll be also happy when someone helps me with this :)

**Comment by sbidolach** [comment]
@legraphista Could you try to download the newest version of nipplejs which is available on the below URL

https://github.com/yoannmoinet/nipplejs/blob/master/dist/nipplejs.min.js

and replace a file in folder `/public/js`?

Please let me know if this issue is still existing. If yes then we have to think about new component or help them solve this issue :)

**Comment by FayneAldan** [comment]
Hey, this is a longstanding issue. Is it going to be fixed...? It think it has something to do with the page being able to be scrolled one pixel.

**Comment by FayneAldan** [comment]
Also, updating that script seems to have fixed the problem.
